In [5]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr [arr % 2 != 0] = -1 
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
import numpy as np

arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [8]:
import numpy as np 

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
import numpy as np

input = np.array([1,2,3])
pattern = np.r_[np.repeat(input, 3), np.tile(input, 3)]

print(pattern)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [11]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

elements = np.intersect1d(a, b)

print(elements)

[2 4]


In [13]:
import numpy as np

np.random.seed(100)
a = np.random.uniform(1,50, 20)

first_5 = np.argpartition(-a, 5)[:5]

print(first_5)



[15 10  3  7 18]


In [16]:
import numpy as np

а = np.array([1,2,3,np.nan,5,6,7,np.nan])
del_nan = a[~np.isnan(a)]

print(del_nan)

[1. 2. 3. 5. 6. 7.]


In [17]:
import numpy as np

a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])

distance = np.sqrt(np.dot(a-b, a-b))
print(distance)

6.708203932499369


In [18]:
import numpy as np

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 
index = np.where(x == 1)[0][n-1]

print(index)

8


In [19]:
import numpy as np

# Input 
np.random.seed(100) 
a = np.random.randint(0, 5, 10)

out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False

print(out)
print('Array: ', a)

[False  True False  True False False  True  True  True  True]
Array:  [0 0 3 0 2 4 2 2 2 2]
